# Enable system clipboard integration
set-option -g set-clipboard on
# Allow tmux to pass clipboard data through to the terminal (OSC 52)
set -s set-clipboard on
set -g allow-passthrough on
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# pick your flavor
set -g @catppuccin_flavor 'mocha'  

set -g @catppuccin_window_text " #I"
set -g @catppuccin_window_current_text " #I"
set -g @catppuccin_window_status_style "slanted"

# initialize TPM (must be last line)
run '~/.tmux/plugins/tpm/tpm'
